image: coq:8.5

buildjob:
  tags:
  - coq
  script:
  - coqc -v
  - 'time make -j8 TIMED=y 2>&1 | tee build-log.txt'
  - 'grep Axiom build-log.txt && exit 1'
  - 'cat build-log.txt  | egrep "[a-zA-Z0-9_/-]+ \(user: [0-9]" | tee build-time.txt'
  - make verify
  only:
  - master
  artifacts:
    paths:
    - build-time.txt
